language: java
jdk:
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
    secure: OFP0IHEWL7kJjCgPuUtyb7vj+Wj9Pb68sioJfgiVmLqDMy5zF6WOj8lb8n3JqjVlHIByIX5CNDY9a8O/QDXqb1NfRcf+26NGEXLv196YSUu3cqjbSKR6nFanbr7ypAtULV9eRoo0SUdaTfhq6x7j2FethyoVjt4bfMheSC4uzNAmEn7fnEEYLOh46hBleV7I2q9hUdhioWnMmouAFRRRw9kGgc7DXeEhytCraXWdYOaBoXkYhNtX/xD86bQPYFQPCFl6IOQZ3pMPSa7kkvhnhUBNn0Muj2UZyZvLrnyGToMZCn0onnhidvAIeL/Q/EaOoFdHySVJFoqreGRFNM4mT6lNHR8dygqGMus9HjP/V638u898B0gcub4lucV+g+z5z6KAi/q+GKSNwP6mduxSy6ztX91uniLP1gZfEU1DPDHA75NO4tIvT7qOVRyhqNn6ri9CKzza5I4523JF+pgAALSrxn4JTWwvfpR9cP+7MjJ4/0+e4OGQvnkLoq9akROFhCb+ntY1Frn7ZX30eUaCKnHANu/75hrKLQWkIVfNTS/N3eoHUxflG6AMW8fX41gFm7pSf4y8PuRUk6D49IciSI6xuoLStsJ+Xvh+Es9W6Kcf4l2tcb4205qKTHgedhCwEg+/wL76t6rmCGQNE7qHhdEv0pB1taP2NWLR6QGWsUw=
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
