language: java
jdk:
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
    secure: IXiBmee5MRxYT2MUWUiu2Uo9EU8tyScbG04IQzcI13AiMIFyU+XFr6rz1yLFrOTSlVoDHXVf8fKDARn6d7vXe/+Ucxyqv2jCuRdJgCKaKOyPPxjdeRvB/+/ezjd0MNOf30WZ72LwawN13cNS/dtfSQiUsZXsPrsY4kCFQaNoFa02V25UwNu0b0EfJOnqQ5/QBZndznJzJfttY3IVsC878tEPXuG2FR1YS3A6dFXC/qkGlG4Vuanp4NqngrIP8QA1zoy2K1aB9ohIQNhKohjtvO4Y/M8hnRrLm0bznEOtHMPAFjpODOhokFki3Np0nYT4LNj/Z8Q5i4cEfJvDF4eQ7rQyAom2Zmu1YAgubv1jb5KpcR0gz7QLuk0GRsszfpblhMETczSCViSXdNzyPKiikQEg4enVDclF4tijkA/WPMMsmbOqOkaD7ZwG3/7sXF6xXp14gUMArmMtKothJulMhSGPBRcxphmTTF3QMHpz4nBJWHNBbINjyBhCt3Dwq59Dw2IAkbxLRgLmPWyqMNUkOZF1WDtNsCacDJK8W78jPs7RgMHa7amF1ZTSsofWzNWk231Azf3TtXcczbaQQL3zBzF+Wenc8qXjrr77tyQHWNdvnfUPRhdqYLcIpkGyhRl9ktH/NougwQSXSAYaAg0/7P/wDuILKn61699OYYQn6gE=
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
