language: java
jdk:
<<<<<<< HEAD
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
=======
  - oraclejdk8
sudo: required
before_install:
 - chmod +x gradlew
>>>>>>> 29074300983565a6338c41703dc2b4bbd1002b5a
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
    secure: GyG3hI++bIx/tKgvZTeUEQBhdjrG1kJt7NgqDaWp6CUVG8eWcjhMEwwOPGObmMKzyTRs/kEKwkO1ey144Hio4dCPuF+Dzd5yoz5cCbK9e4rmVXhKflyk6EMBzSjUhqzDzKlljNs67UubwzZSYli110HnRWrouPzmeR9Y6djBfRGU3Z4BbnhRe8KIZwU42Uo5qoryEfTp5G2IncSKLif7b871Y9BVry526DUAfFVa8iQF9yAjT4GVFSf3rtNVAn0EM6Gnf5UxbSi1JPUyZUZnDS/gMRNlWzUySNuLIACCF9R/LQxXUz+g/+dndLf+sC9KOzqZ9thSmhhZccy9m3XzDbTPfoRzbAuqZ7QSOIYsY+lgw6azo6F5asRvFh5H+tbyELSFWb9uOXY+DLmtX7qTM7eb9vAMiqjm1veCMEdy63MuyzZXfRvJOLXJCCOx6k2WgL6v2oh9D2l5oEYVS5JOJZ28/3qm6W9LZTcRnKhHNujMVLr9+Mc8yJWBeEbIkMXiQ53i+tl42ukQh4R4ByKQwz6iFAgX2cJfajPy2SYOfuFO9tqV5m2sv52LotBpku0z8xpJEjbqIhhwisorqrDLApRG5hFIuzOYCZFYcZvCoyNoT2AIspNvMjM8qkyT878tYpHvAMv0rNJSp+zl16Lww31WaAMvIJ5/xijqLZ26xAk=
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
