language: java
jdk:
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
  secure: "BEhDkGkTQUfbLWTfCsXkOXy3py62VNKYdxwmNHTApjPHROJb7DR660KXtlsmTSwPE4HoXHonJ0u5ckZmNj0SMAJQNLiOww/TCsDxlW7KX8MMH8A2rYzqnKaJHNBkYzgp8juWAZNA+xZTUJuDBxBdlfDGW9q72musIprVJkjPuW41odgsZcHn0jgriV6P/k5nqFyBhKvRH6QvGWw35RTg+AQmgkPuzJM0s9iZWl9AHAE1cNxpzmi6eUAD4GzbJGBcDwCGfxifQBuZZhzNRJ8x97wBdLd7ULFa0le7cGDmRCehwLpNwGSYbKaokMIJMgH10fHp8sUWMmWL27SxHz8VyEdn4VdqQWIAzhZC82IZgDwmyw+T2VwPWZy6rnXvYqI892PD48fhWC6/16BFDIoaikpFdwMOMIjNuO8ZNg7KwV7x6Pq8xrr8Z3EiUSIiu+ioPdMUuX8KPUZAIt6FX1DKixISxlrqrAsq6iwIGI34mDi2uZaDJV5RNC2xCSesLMn5nh0on0zWETp7Jv/IYT2+Y0XfXTc0XFPzu+38etcCxqSvadiaO1ecbsIorwRlzyP4frN1qMSDx8JSBa3WQgbXCIZKK0SjhHgVApd/9QNRHxAmwRTyX6mPdPydv7rRrLKIys+d08Js+m+u4iPL1w9tMsEFAW4FV9+KWwIRFAnfYoI="
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
