language: java
jdk:
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
    secure: Xip3iSiuLqqKY1wm0fBfc1CdHmu4aA/D2xwny5mW6Ef4y5yGIQCHbBUNffqs7Q2pYd7gP8u3PJOVOfbr9LnGXpYnyNOu+gjK8OBuBJPGtWefy2ZKbgQ5H9dgkGJDObQZvj2z6ZZ3z7syQT8OAtoykkSXpXE+gVyj8vsgklurMCd6EN+J4YaZp32W3dS1U46PCUq1u9ZjrMzSm8DvYTdd9PJBmjRTBQYhXBS+EqFFzfshsByy3AS9S+7+LbJmC47ikdeQphpkoTQa1IGI0BtqjluTzs8/r+y8Uhm1XPis1zIODo3G6L+2aEMespTOOIkSiTPZHsNYUUCcYFFCiseUb/sWR5tu5RPVUbW2nwQ4A4VutdjlZ2xB21NA/v2pi4bC4VLk8WsUpTdKsZjU+91RzN2pDF88HaJ4TUbZl8mV565GLk/OL6AceDV5Vc8xKduXjFWhBPIcWCh1wdpz5DOf6VVzL0DmO1BJYXRvciB25iJKn4TOnQu7G0XWMtNaaZPKKpAjXU7FLFm3g0LP6nC3tGdq8S+F0HCcDrIimxJjJSns81y41ZhI393V3rD6s3j0ui5K89pTyiKbTdpcUEfqk2GZVlnrS0dzbz/czbMlQnieLzZn1Ypv4nSQiHiG3LqwMtfgnl+cK6bG1eb+j10TJItZ2lc97ZOI+aK7ZowFRhw=
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
