language: java
jdk:
- oraclejdk8
sudo: required
before_install:
- chmod +x gradlew
edge: true
deploy:
  provider: cloudfoundry
  api: https://api.run.pivotal.io
  username: jli5@andrew.cmu.edu
  password:
    secure: 2urYCxTG/HIB3hlB7PFfi/f8ocWwGlG8plclv1YLN+fQiHTv1ygXphkIUPyAAfcxWp2eA6sUl5MSkfB94KAGbpumOxQAt7K1FgdGYMC/G2x7XYKxCxHO6bLV09jW1HeXYpBK4UyWVABsNxtMZO/yNR6ZJ9ecBQBTVdM+FJXag6QripmrBrtGNQj8oFIqwttK/EAo9ClOVMaGAjpr1Ux07C/pqI7YjCF28FubkS1ZXriFUd2HBlDabdi7U5BXqIqT/8uKZ+qvprXNBuB2JWTTwKqLVkXBTseRWhZXY0X1qvDi4iY8tX3PkHminFNTSITFdy8HoMHeG/WIOBHIvQWXq65GEHLASOV69SqCkxNd+W6sCd6T4czLTMJxubQUbJgVMeY9Qz/Uqy/HLy8R5kY8MBYeKZyPT8wnAuTYrs5EUNIMHmrEKdejlF2BaIERMEwvcDuDoQRQVkQvntqAqqUfAmVJYDqaNYdTR4K5CiEThjBEVtP0L8lNI0Ai1HxXIGPGN9tKC3VUG5DeO/VKORc8CB+3oQ7a0pkP9o4FK+Kx1HrSeGMu+FxcT1kvU4/oABjzmZuKXMOjfiZY2LZKI3NPHmYWZHlXxQPmYLWEHL2yu2NhoRltF3eSAKzR2Mm5WZvblawK09rBt7Zpj27tyUxWSRrejhMtQrOo9J/WfIjwnDU=
  organization: CCFB
  space: development
  on:
    repo: jli5/Image-Gallery-Application
